name: sixzero
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-autoprefixer
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
google_analytics: UA-110588115-1
url: https://sixzero.co
