name: sixzero
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-autoprefixer
exclude:
  - buildScripts
  - yarn.lock
  - package.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
google_analytics: UA-110588115-1
url: https://sixzero.co

